### ISSUE TITLE
Support to "Automatic speech recognition" feature

### ISSUE THREAD

**Issue by felipehw** [flathub/org.parlatype.Parlatype#1]
At the official site, [they say](https://www.parlatype.org/features.html) this feature ("Automatic speech recognition") is optional and may be turned on at build time and used with the parameter "--with-asr".

I tried with the Flatpak version but it seems that it was built without support to this feature.

Could we have this enabled?

**Comment by gkarsay** [comment]
The new version 2.1, published today, can be used `--with-asr` again.
